"""Add user_id to medical data tables

Revision ID: a7edb851a5b6
Revises: da4107b18aee
Create Date: 2026-04-15 12:06:20.066010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7edb851a5b6'
down_revision: Union[str, Sequence[str], None] = 'da4107b18aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('message', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'users', ['user_id'], ['id'])
    op.drop_column('alerts', 'threshold')
    op.drop_column('alerts', 'timestamp')
    op.drop_column('alerts', 'vital_type')
    op.drop_column('alerts', 'value')
    op.add_column('conversations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('title', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.drop_column('conversations', 'session_id')
    op.drop_column('conversations', 'ended_at')
    op.drop_column('conversations', 'started_at')
    op.add_column('lab_results', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lab_results_id'), 'lab_results', ['id'], unique=False)
    op.create_foreign_key(None, 'lab_results', 'users', ['user_id'], ['id'])
    op.add_column('medications', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_foreign_key(None, 'medications', 'users', ['user_id'], ['id'])
    op.add_column('messages', sa.Column('role', sa.String(), nullable=True))
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_column('messages', 'sender')
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    op.add_column('reports', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.drop_column('reports', 'report_type')
    op.add_column('vitals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vitals_id'), 'vitals', ['id'], unique=False)
    op.create_foreign_key(None, 'vitals', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vitals', type_='foreignkey')
    op.drop_index(op.f('ix_vitals_id'), table_name='vitals')
    op.drop_column('vitals', 'user_id')
    op.add_column('reports', sa.Column('report_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_column('reports', 'user_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_column('patients', 'user_id')
    op.add_column('messages', sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_column('messages', 'role')
    op.drop_constraint(None, 'medications', type_='foreignkey')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_column('medications', 'user_id')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.drop_index(op.f('ix_lab_results_id'), table_name='lab_results')
    op.drop_column('lab_results', 'user_id')
    op.add_column('conversations', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'title')
    op.drop_column('conversations', 'user_id')
    op.add_column('alerts', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('vital_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_column('alerts', 'created_at')
    op.drop_column('alerts', 'severity')
    op.drop_column('alerts', 'message')
    op.drop_column('alerts', 'user_id')
    # ### end Alembic commands ###
